name: firestore_ui
description: A port of firebase_database's FirebaseAnimatedList
version: 1.12.0
homepage: https://github.com/gildaswise/firestore_ui
# author: Gildásio Filho <gildasiogx@gmail.com>

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6 
  firebase_core: ^0.5.1
  firebase_core_platform_interface: ^2.0.0
  cloud_firestore: ^0.14.2
  cloud_firestore_platform_interface: ^2.1.3
  flutter_staggered_grid_view: ^0.3.2
  collection: ^1.14.13

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
