name: firestore_ui
description: A port of firebase_database's FirebaseAnimatedList
version: 1.8.0
author: Gildásio Filho <gildasiogx@gmail.com>
homepage: https://github.com/gildaswise/firestore_ui

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6
  firebase_core: ^0.4.4
  firebase_core_platform_interface: ^1.0.2
  cloud_firestore: ^0.13.2+1
  cloud_firestore_platform_interface: ^1.0.0
  flutter_staggered_grid_view: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
